### ISSUE TITLE
Laravel 7

### ISSUE THREAD

**Issue by theVannu** [offline-agency/laravel-mongo-auto-sync#36]
Hello, I try to install the package through composer but it didn't work.
I know that the project is not ready for Laravel 7 (according with the documentation).

There is a way for install the package in Laravel 7? I try with "offlineagency/laravel-mongo-auto-sync": "dev-develop" in my composer.json with following error:

```
Problem 1
    - The requested package offlineagency/laravel-mongo-auto-sync could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by Giacomo92** [comment]
Hi @theVannu, we have just release an [alpha release ](https://github.com/offline-agency/laravel-mongo-auto-sync/releases/tag/2.0-alpha.2)

**Comment by theVannu** [comment]
Hello @Giacomo92 , thank you for help
