### ISSUE TITLE
Increase Test coverage

### ISSUE THREAD

**Issue by Giacomo92** [offline-agency/laravel-mongo-auto-sync#48]
- [ ] #52 [syncUtils.php](https://github.com/offline-agency/laravel-mongo-auto-sync/blob/master/src/syncUtils.php)
- [ ] #54 [MongoCollection](https://github.com/offline-agency/laravel-mongo-auto-sync/blob/master/src/Extensions/MongoCollection.php)
- [x] MDModel
- [ ] Helper
- [ ] ModelAdditionalMethod
- [ ] Sync cases
- [ ] DropCollection
- [ ] GenerateModelDocumentation

**Comment by davidribeiro** [comment]
Hello @Giacomo92 
I can take care of this if you want
Any thing I should know beforehand?

**Comment by Giacomo92** [comment]
Hi @davidribeiro , you can start by read our [docs](https://docs.offlineagency.com/laravel-mongo-auto-sync/). If you have any questions just ask. [Here](https://codecov.io/gh/offline-agency/laravel-mongo-auto-sync/branch/master) you can see master code coverage. Create a PR from that branch please.
