### ISSUE TITLE
Could not find a matching version of package offlineagency/laravel-mongo-auto-sync.

### ISSUE THREAD

**Issue by LittleTom** [offline-agency/laravel-mongo-auto-sync#67]
There has an error thrown when I installing laravel-mongo-auto-sync.
How should I do. Please help me. thank you

`Could not find a matching version of package offlineagency/laravel-mongo-auto-sync. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (dev).`

I'm using following laravel 9 and jenssegers/mongodb 3.9x

**Comment by nomitoor** [comment]
Do you find any answer regarding this issue ?

**Comment by LittleTom** [comment]
> Do you find any answer regarding this issue ?
Use this code to get package, I think the original author wrote the wrong code.
`composer require offline-agency/laravel-mongo-auto-sync`

**Comment by SanaviaNicolas** [comment]
@LittleTom Thanks for reporting the issue. Closed via #70
